name: randomspotfinder
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  cloud_firestore: ^4.16.0
  firebase_auth: ^4.19.0
  google_sign_in: ^6.2.1
  flutter_fortune_wheel: ^1.3.1
  rive: ^0.13.1
  geolocator: ^11.0.0
  http: ^1.2.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/rive/roullette_button.riv
    - assets/test/test.json
